### ISSUE TITLE
Crashes upon equipping an enchanted piece of armour

### ISSUE THREAD

**Issue by KorberryTea** [RedLime/DetailArmorBar#1]
As per the title, the mod crashes after equipping an enchanted piece of armour and will keep crashing upon trying to return to the world in which the armour is equipped.
I replicated the crash a few times, using different enchantments and different pieces of armour.

Here is the crash report. The only mods used are Detailed Armor Bar, Fabric API, Kotlin, and Not Enough Crashes (and of course, the mod crashes without Not Enough Crashes as well). 

[crash-2021-07-24_14.11.48-client.txt](https://github.com/RedLime/DetailArmorBar/files/6872374/crash-2021-07-24_14.11.48-client.txt)

**Comment by RedLime** [comment]
What is your MC version?
It isn't 1.17.1?
