### ISSUE TITLE
Armor Bar Enchament goes beyond boundary

### ISSUE THREAD

**Issue by Herobrine2143** [RedLime/DetailArmorBar#10]
When having custom enchantments, the enchantment aura goes beyond the boundary of the armor bar.

![image](https://user-images.githubusercontent.com/22053132/131417372-64f3c03e-7406-43ae-a646-92d92e992dfa.png)

The elytra in this case has all protection enchantments to level 5.

Minecraft Fabric 1.17.1; Mod Version 2.4

**Comment by RedLime** [comment]
This problem was there from the 1.0 lol.
But I was worried about what to do, and it hasn't been fixed yet.
Because it seemed okay not to fix it

**Comment by Herobrine2143** [comment]
Why not color change the aura colors? For instance, we can say that the yellow aura is the base color, when going beyond the limit, change the color to orange corresponding to their amount of auras it has.

**Comment by RedLime** [comment]
> Why not color change the aura colors? For instance, we can say that the yellow aura is the base color, when going beyond the limit, change the color to orange corresponding to their amount of auras it has.

Orange color is fire protection.
It is displayed like that because all protections were 5, but now I see some bugs.

If your fire protection is level 5, that is a probably bug.

**Comment by RedLime** [comment]
Fixed in 2.4.1
