### ISSUE TITLE
[Suggestion] Allow for inverse sorting order

### ISSUE THREAD

**Issue by ShaneTRS** [RedLime/DetailArmorBar#12]
An option to switch the order of the armor pieces in your armor bar.

Instead of sorting top to bottom: helmet, chestplate, leggings, boots. It would sort bottom to top: boots, leggings, chestplate, helmet.
So wearing a gold helmet would put the gold piece at the very end of your armor bar, instead of at the beginning.

**Comment by RedLime** [comment]
Added in 2.6 version. thanks for your suggestion.
