### ISSUE TITLE
[Suggestion] Allow for positional special items

### ISSUE THREAD

**Issue by ShaneTRS** [RedLime/DetailArmorBar#13]
Enabling this setting would place an item in the chestplate slot before the helmet slot:
(the screenshot has the armor items sorted from bottom to top, with boots and leggings showing first)
![image](https://user-images.githubusercontent.com/80662335/134428185-0c58f6e5-50c4-448b-86ff-0097b848a861.png)

**Comment by RedLime** [comment]
What, It is bug. It should be sorted originally.
What is your version, modloader?

**Comment by ShaneTRS** [comment]
This is a feature suggestion, there is no bug.

**Comment by RedLime** [comment]
Not sorted that is bug. 
It's sorted in fabric 1.17.

**Comment by RedLime** [comment]
![image](https://user-images.githubusercontent.com/25276450/134440519-f2fcd1da-9579-40d7-8286-47ad0d78ccb3.png)
![image](https://user-images.githubusercontent.com/25276450/134440526-9c6263c6-73e6-4459-b250-831b16efb5ae.png)
As with #12, I didn't find any issues.

**Comment by ShaneTRS** [comment]
This GitHub issue and #12 are both feature suggestions/requests. They're not bug reports

**Comment by RedLime** [comment]
It means that you already have that feature.
If those features don't work, it's a bug.

**Comment by ShaneTRS** [comment]
If they're already features, how do I enable them?
I didn't see them in the config

**Comment by RedLime** [comment]
There are no config. It just default features.
That's why I asked for the version.

**Comment by ShaneTRS** [comment]
2.5, Fabric 1.17.1.

Based on your screenshot, it is **not** a feature enabled by default. If it was, then your elytra would be inbetween the netherite and iron gear on your armor bar.
This is a feature request for a feature that isn't implemented currently.

As for #12, the current system puts your gear onto the armor bar top to bottom.
You perfectly showed that in your screenshot: your iron helmet is on the left of the occupied space on the armor bar, not at the end of it.
That feature request is for asking a way to toggle it between having it show bottom to top, instead of top to bottom.
Sorting bottom to top would place your boots on the left of the occupied space on the armor bar, not at the end of it.

**Comment by RedLime** [comment]
Added in 2.6 version. thanks for your suggestion too.
