### ISSUE TITLE
Incompatability with Health Overlay

### ISSUE THREAD

**Issue by milkev** [RedLime/DetailArmorBar#14]
When using [health overlay](https://www.curseforge.com/minecraft/mc-mods/health-overlay-fabric), the armor bar added by detail armor bar still moves upwards as if there is extra lines of vanilla hearts, but there is no extra lines of vanilla hearts.
![image](https://user-images.githubusercontent.com/22010128/134523681-d693b410-7aad-4da6-9702-7e6244f46a62.png)

**Comment by RedLime** [comment]
Added Compatibility Mode in Option on 2.6 version. Thanks :D
