### ISSUE TITLE
Animations are applied incorrectly with new sorting options

### ISSUE THREAD

**Issue by ShaneTRS** [RedLime/DetailArmorBar#16]
Screenshot of GUI with heavily damaged Elytra
![image](https://user-images.githubusercontent.com/80662335/134991105-e931dac2-2b65-437a-8f7a-95212e746bfe.png)

**Comment by RedLime** [comment]
It's not a bug.  Durability warnings are displayed as many as Armor Points from the far right.

**Comment by ShaneTRS** [comment]
In this screenshot I have fire protection iron leggings on
![image](https://user-images.githubusercontent.com/80662335/135196704-8d5c721b-6a50-4661-b1af-2f892fa69a38.png)

**Comment by RedLime** [comment]
Yes. They don't fit in each per armor slots. It just shows as levels(enchantments, durability, and etc) to both side in armor bar.

**Comment by ShaneTRS** [comment]
Ah thanks
