### ISSUE TITLE
Leather Dye on Armor Bar not showing on specific server

### ISSUE THREAD

**Issue by Tenuuu** [RedLime/DetailArmorBar#17]
The server I play on is Origin Realms and they use dyed armor as their custom items but they always show up as iron armor on the bar. Saw someone else have their armor bar show up properly according to the armor so that's why i'm confused

**Comment by RedLime** [comment]
can u give me server url?

**Comment by Tenuuu** [comment]
play.originrealms.com Here it is!

**Comment by RedLime** [comment]
I just played on the server, and my guess is that's not a normal leather armor.
My guess is that the leather armor may have included another NBT tag (for special texture packs), or it may not be the leather armor at all.
More detailed debugging is needed, but there's nothing I can do right now.

**Comment by Tenuuu** [comment]
Ahh, okay! Thank you for looking into it!
