### ISSUE TITLE
Feature request: color armor sprites by material

### ISSUE THREAD

**Issue by catgirldoll** [RedLime/DetailArmorBar#2]
**Feature request:**
Show armor types and the amount of armor contributed for each in the armor bar, similar to the deprecated mod [Armor Chroma](https://github.com/mccreery/armor-chroma). I may be incorrect here, but I imagine this would be as simple as adapting the netherite armor bar code to also handle sprites for turtle, leather, gold, chainmail, iron and diamond armor. An elytra indicator could be useful too!

Example:
![Armor Chroma](https://i.imgur.com/UiMQ2SM.png)

I edited `armor_bar.png` with some quick sprites for each type of armor. Bear in mind my iron armor bar sprites are different in color to the vanilla armor bar: iron textures are less "blue"
![armor_bar.png](https://user-images.githubusercontent.com/20545957/128119155-45e44e1a-e87e-4b3f-8a3f-7774d1da2c85.png)

**Comment by RedLime** [comment]
wooo, that's cool.
I'm working on another mod now.  I will update as soon as the another mod is done.

**Comment by catgirldoll** [comment]
Awesome! Just FYI I also just added an elytra sprite to that image :)

**Comment by RedLime** [comment]
![image](https://user-images.githubusercontent.com/25276450/128593514-fdeac656-3189-4f2d-a270-5d0cfa722389.png)
Update on 1.3 version :) thx for made texture
