### ISSUE TITLE
[Forge 1.19] Mod crashes on 41.0.64

### ISSUE THREAD

**Issue by Autovw** [RedLime/DetailArmorBar#27]
A big rendering refactor PR has been merged into Forge which affects a bunch of client-side mods, including Detail Armor Bar. ([Reference](https://forge-render-refactor.notion.site/forge-render-refactor/ecd69011d01042c48a0fca80696cb4da?v=dd40865450614d9c9130c3dedcd085e5
))

My initial plan was to do a PR to help you out, but it looks like this repository isn't up-to-date with a 1.19-forge branch.

**Comment by RedLime** [comment]
Currently, for unknown reasons, Forge 1.19 cannot work in my development environment.
Could you make a new brunch yourself? I heard about updated to can do that recently by Github.

**Comment by Autovw** [comment]
Sure, I'll give it a try.

**Comment by RedLime** [comment]
Updated in 2.6.3, thank for your contribution :D
