### ISSUE TITLE
Incorrectly rendering horse health when in survival/adventure

### ISSUE THREAD

**Issue by catgirldoll** [RedLime/DetailArmorBar#3]
~~When both Detail Armor Bar and [HWYLA Addon HorseInfo](https://github.com/smujaddid/hwyla-addon-horseinfo) are loaded, the horse health bar renders incorrectly. This does not happen with only one of the two mods, and happens whether or not a version of WAILA/HWYLA/WTHIT is loaded.~~
~~This is in a fresh Minecraft instance and world:~~
~~[MultiMC Log](https://paste.ee/p/ssu74)~~
~~[image](https://user-images.githubusercontent.com/20545957/128409063-df2de420-ad83-4647-b044-7b3a7e1f31ec.png)~~

~~I've [cross reported this to HWYLA Addon Horseinfo](https://github.com/smujaddid/hwyla-addon-horseinfo/issues/1), and will delete the report here if it turns out your mod is not at fault.~~

**UPDATE: I have replicated the issue in a fresh instance with only DetailArmorBar, FabricLanguageKotlin and FabricAPI present.**
[MultiMC Log](https://paste.ee/p/UHvvG)
![image](https://user-images.githubusercontent.com/20545957/128422719-7ae473e9-3f5c-4ee2-b93c-dd0dfdf2d23f.png)
When in creative mode, the horse's health renders correctly. I presume this is because DetailArmorBar (or the armor bar in general) is not called when in creative.

**Comment by RedLime** [comment]
will fix in 1.3 :)

**Comment by RedLime** [comment]
![image](https://user-images.githubusercontent.com/25276450/128593650-0f7a34e9-b498-4738-a040-e9d03999351c.png)
Resolved in 1.3 :>
