### ISSUE TITLE
Include armor from other source (like bonus stat)

### ISSUE THREAD

**Issue by ardissaps** [RedLime/DetailArmorBar#32]
Would you please include armor value to the bar from others source of armor bonus?
As example [PlayerEx ](https://modrinth.com/mod/playerex)have armor bonus that are from stats. (It is not bug, kind of feature request, no need to be hurry)
![image](https://user-images.githubusercontent.com/82106625/188150367-276dfc66-917c-4eb1-a18b-4e210338409c.png)

**Comment by RedLime** [comment]
I saw PlayerEx issue, I'll wait that pull request :)

**Comment by ardissaps** [comment]
> I saw PlayerEx issue, I'll wait that pull request :)

Hello there! Look like the pull request arrived! :p 
https://github.com/RedLime/DetailArmorBar/pull/33
