### ISSUE TITLE
Incompatible with Raised

### ISSUE THREAD

**Issue by SAJewers** [RedLime/DetailArmorBar#38]
https://mclo.gs/e8p04kO

**Comment by HaXrDEV** [comment]
Can confirm, experiencing crashing on my end as well: https://mclo.gs/PvcCVwH

**Comment by SAJewers** [comment]
Raised fixed it on their end.

**Comment by midvightmirage** [comment]
![Image](https://github.com/user-attachments/assets/396acba9-ec23-4044-946a-8df9db732ecc)

**Comment by midvightmirage** [comment]
they didnt

**Comment by midvightmirage** [comment]
nvm im stupid i read it wrong it was a crash omg this is exactly why i dont use github ever
