### ISSUE TITLE
Armor Bar not showing the proper Armor Values

### ISSUE THREAD

**Issue by Herobrine2143** [RedLime/DetailArmorBar#4]
While trying to test a different mod, I found out about this bug, I've given myself a **custom golden chestplate** with **99 Defense Armor Points** but the mod only displays the Armor Point values of the original golden chestplate which 5 (2.5) Armor Points.
![image](https://user-images.githubusercontent.com/22053132/130157674-9bb11dc8-a876-443a-b084-3080d67cd707.png)

I'm using version 2.0.1 of the mod, the older version 2.0.0 did not have this issue, version of minecraft is 1.17

**Comment by RedLime** [comment]
It can be fix.
However, the Detail Armor Bar currently does not support armor points greater than 20.

**Comment by RedLime** [comment]
Fixed in 2.0.2
