### ISSUE TITLE
[Bug/Mod Compact] Incompatible with Overflowing Bars mod

### ISSUE THREAD

**Issue by MbtMarco** [RedLime/DetailArmorBar#42]
**https://modrinth.com/mod/overflowing-bars**

![image](https://github.com/RedLime/DetailArmorBar/assets/124934175/a09181ad-1d82-45db-ba69-7900300ff9f1)

**Comment by RedLime** [comment]
Duplicated. close.

**Comment by MbtMarco** [comment]
Sorry, i didnt close this.
