### ISSUE TITLE
2.3.1~2.6.1 variant on Modrinth: upload policy issues

### ISSUE THREAD

**Issue by 3gf8jv4dv** [RedLime/DetailArmorBar#56]
Within the scope of these versions, I noticed that you put different loader variants and even 1.16.5 and 1.17.1 in the same version release. This caused some launchers with the update mod feature to make incorrect choices when performing update operations.

I know you have adopted a different policy in subsequent version releases, but the situation with these specific versions has caused some unnecessary confusion: some launcher developers often receive false positives related to this (called false positives because this has nothing to do with the design logic of the launcher).

Could you please make some adjustments to Modrinth's upload? Regards.

**Comment by RedLime** [comment]
fixed it, thanks!
