### ISSUE TITLE
Dependency Cloth is not marked as dependency in the fabric.mod.json file.

### ISSUE THREAD

**Issue by K0-RR** [RedLime/DetailArmorBar#7]
I saw you removed the cloth from the jar which is good but you forgot to add it here https://github.com/RedLime/DetailArmorBar/blob/1.17/src/main/resources/fabric.mod.json#L30.

**Comment by RedLime** [comment]
> I saw you removed the cloth from the jar which is good but you forgot to add it here https://github.com/RedLime/DetailArmorBar/blob/1.17/src/main/resources/fabric.mod.json#L30.

No, I mean Cloth Config is no longer use.
That is why I didn't add that.

after version 2.3, Detail Armor Bar's options are changed to my Screen code, so now no additional APIs are used.

**Comment by K0-RR** [comment]
Ahhh that's even better, sorry that I misunderstood.
