### ISSUE TITLE
Armor Bar shift offset

### ISSUE THREAD

**Issue by Herobrine2143** [RedLime/DetailArmorBar#8]
when you have a second health bar the armor doesn't shift properly and overlays with the second health bar.

![image](https://user-images.githubusercontent.com/22053132/130969591-bb0ea544-1a25-41b2-825b-6a5ad07a7903.png)

Version of the mod 2.3; Minecraft 1.17.1

**Comment by RedLime** [comment]
is Fabric?

**Comment by Herobrine2143** [comment]
Yes

**Comment by RedLime** [comment]
Fixed in 2.3.1
